#!/bin/bash
#
# 主要是分析 dovecot 这个服务，这个服务是 FC3 提供的 pop 登入管理机制。
# 同样是分析 /var/log/maillog 
# 这个程序改自 pop3 的程序！
#
#####################################################################
# 3 POP3 的登录资料的功能函数
funcdovecot () {
	echo "================= POP3 的登录档资料整理 ======================"	>> $logfile
	pop3right=`cat $basedir/maillog|grep "pop3.*Login:" |  wc -l | \
		awk '{print $1}'`
	if [ "$pop3right" != "0" ]; then
		echo "POP3登入次数: $pop3right" | \
			awk '{printf( "%-40s %4d\n", $1, $2)}'			>> $logfile
		echo "帐号   来源地址 次数 "|  \
			awk '{printf("%-6s %-15s %-25s %-4s\n", " ", $1, $2, $3)}'	>> $logfile
		cat $basedir/maillog | grep "pop3.*Login:" |\
			sed 's/^.*Login://g' | awk '{print $1}' \
			> $basedir/maillogpop-1
		cat $basedir/maillog | grep "pop3.*Login:" |\
			sed 's/^.*Login://g' | sed 's/^.*\[//g' |\
			sed 's/\].*$//g' | awk '{print $1}' \
			> $basedir/maillogpop-2
		paste $basedir/maillogpop-1 $basedir/maillogpop-2 \
			> $basedir/maillogpop
		/bin/awk '{ for( i=0; i<1; i++ ) Number[$i]++ };
			END{ for( course in Number )
			printf( "%-35s %4d\n", course, Number[course])}' \
			$basedir/maillogpop   | sort -k 3 -gr | \
			awk '{printf("%-6s %-15s %-25s %3d\n", " ", $1, $2, $3)}'		>> $logfile
		echo " "                                                        >> $logfile
	fi
	pop3error=`cat $basedir/messageslog|grep "pop3.*Login fail"| \
		 wc -l |  awk '{print $1}'`
	if [ "$pop3error" != "0" ]; then
		echo "POP3错误登入次数: $pop3error" | \
			awk '{printf( "%-40s %4d\n", $1, $2)}'			>> $logfile
		echo "帐号   来源地址 次数 "|  \
			awk '{printf("%-6s %-15s %-25s %-4s\n", " ", $1, $2, $3)}'	>> $logfile
		cat $basedir/messageslog | grep "pop3.*Login fail" |\
			sed 's/^.*user=//g' | awk '{print $1}' \
			> $basedir/maillogpopno-1
		cat $basedir/messageslog | grep "pop3.*Login fail" |\
			sed 's/^.*host=//g' | sed 's/^.*\[//g' |\
			sed 's/\].*$//g' | awk '{print $1}' \
			> $basedir/maillogpopno-2
		paste $basedir/maillogpopno-1 $basedir/maillogpopno-2 \
			> $basedir/maillogpopno
		/bin/awk '{ for( i=0; i<1; i++ ) Number[$i]++ };
			END{ for( course in Number )
			printf( "%-35s %4d\n", course, Number[course])}' \
			$basedir/maillogpopno | sort -k 3 -gr | \
			awk '{printf("%-6s %-15s %-25s %3d\n", " ", $1, $2, $3)}'		>> $logfile
			echo " " 						>> $logfile
	fi
	if [ "$pop3error" == "0" ] && [ "$pop3right" == "0" ]; then
		echo "今日沒有使用 POP3 的记录"					>> $logfile
		echo " "							>> $logfile
	fi
}

