#!/bin/bash
#
# 主要分析 openwebmail 这个服务所产生的 logfile 资料，
# 分析的是 /var/log/openwebmail.log 这个档案
# 目前仅分析
#	1. 登入次数
#	2. 错误登入次数
#	3. 传送电子邮件次数！
#
#####################################################################
# Openwebmail 的登录资料的功能函数
funcopenwebmail () {
	echo "================= Openwebmail 的登錄檔資訊彙整 ======================="	>> $logfile
	grep "$y" /var/log/openwebmail.log > $basedir/openwebmaillog

	# 1. 先取得成功登入的次数！
	testing1=`grep 'login' $basedir/openwebmaillog | grep -v error`
	if [ "$testing1" != "" ]; then
		echo "成功登入 OpenWebmail 的次数统计："					>> $logfile
		echo "帐号 来源 次数" | \
			awk '{printf("%-6s %-10s %-15s %-4s\n", " ", $1, $2, $3)}'		>> $logfile
		grep 'login' $basedir/openwebmaillog | grep -v error | awk '{print $9 " " $8}'|\
			sed 's/(//g' | sed 's/)//g' | sort |\
			awk '{ for( i=0; i<1; i++ ) Number[$i]++ };
				END{ for( course in Number )
				printf( "%-25s %3d\n", course, Number[course])}' |\
			sort -k 3 -gr  | \
			awk '{printf("%-6s %-10s %-15s %3d\n", " ",$1, $2, $3)}'		>> $logfile
		echo " "									>> $logfile
		testing2=`grep 'send message' $basedir/openwebmaillog`
	fi

	# 2. 如果有登入过，并且找到有送出邮件时
	if [ "$testing2" != "" ]; then
		echo "利用 OpenWebmail 发送出信件的次数统计："					>> $logfile
		echo "帐号 来源 次数" | \
			awk '{printf("%-6s %-10s %-15s %-4s\n", " ", $1, $2, $3)}'		>> $logfile
		grep 'send message' $basedir/openwebmaillog | awk '{print $9 " " $8}'|\
			sed 's/(//g' | sed 's/)//g' | sort |\
			awk '{ for( i=0; i<1; i++ ) Number[$i]++ };
				END{ for( course in Number )
				printf( "%-25s %3d\n", course, Number[course])}' |\
			sort -k 3 -gr  | \
			awk '{printf("%-6s %-10s %-15s %3d\n", " ",$1, $2, $3)}'		>> $logfile
		echo " "									>> $logfile
	fi
	
	# 3. 错误登入次数
	testing3=`grep 'login' $basedir/openwebmaillog | grep error`
	if [ "$testing3" != "" ]; then
		echo "登入失败 OpenWebmail 的次数统计："					>> $logfile
		echo "帐号 来源 次数" | \
			awk '{printf("%-6s %-10s %-15s %-4s\n", " ", $1, $2, $3)}'		>> $logfile
		grep 'login' $basedir/openwebmaillog | grep  error | awk '{print $9 " " $8}'|\
			sed 's/(//g' | sed 's/)//g' | sort |\
			awk '{ for( i=0; i<1; i++ ) Number[$i]++ };
				END{ for( course in Number )
				printf( "%-25s %3d\n", course, Number[course])}' |\
			sort -k 3 -gr  | \
			awk '{printf("%-6s %-10s %-15s %3d\n", " ",$1, $2, $3)}'		>> $logfile
		echo " "									>> $logfile
	fi

	# 4. 都沒有任何资讯的時候！
	if [ "$testing1" == "" ] && [ "$testing2" == "" ] && [ "$testing3" == "" ] ; then
		echo "本日沒有任何 Open Webmail 的资讯～"					>> $logfile
		echo " "									>> $logfile
	fi
	echo " "										>> $logfile
}
